module.exports = {
    products: require('./products/products'),
    search: require('./products/search'),
    detail: require('./products/detail'),
    add: require('./products/add'),
    create: require('./products/create'),
    edit: require('./products/edit'),
    update: require('./products/update'),
    remove: require('./products/remove'),
    addCategory: require('./products/addCategory'),
    createCategory: require('./products/createCategory'),
    editCategory: require('./products/editCategory'),
    updateCategory: require('./products/updateCategory'),
    removeCategory: require('./products/removeCategory'),
};
