'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert(
            'Images',
            [
                {
                    file: '1p-totoro.jpg',
                    main: true,
                    productId: 1,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '2e-diana.jpeg',
                    main: true,
                    productId: 2,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '3p-girlWhite.jpeg',
                    main: true,
                    productId: 3,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '4d-marilyn.jpg',
                    main: true,
                    productId: 4,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '5i-loves.jpg',
                    main: true,
                    productId: 5,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '6f-girlColor.jpg',
                    main: true,
                    productId: 6,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '7p-lost.jpeg',
                    main: true,
                    productId: 7,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '8c-girl.jpg',
                    main: true,
                    productId: 8,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '9f-marilynSad.jpeg',
                    main: true,
                    productId: 9,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '10p-flores.jpg',
                    main: true,
                    productId: 10,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '11c-monkey.jpeg',
                    main: true,
                    productId: 11,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '12c-primavera.jpeg',
                    main: true,
                    productId: 12,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '13d-faces.jpeg',
                    main: true,
                    productId: 13,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '14c-ali.jpeg',
                    main: true,
                    productId: 14,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '15c-eggs.jpeg',
                    main: true,
                    productId: 15,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '16c-espectros.jpeg',
                    main: true,
                    productId: 16,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '17f-bowie.jpeg',
                    main: true,
                    productId: 17,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '18i-conectados.jpeg',
                    main: true,
                    productId: 18,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '19d-oneDay.jpeg',
                    main: true,
                    productId: 19,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '20c-queen.jpeg',
                    main: true,
                    productId: 20,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '21c-aitana.jpeg',
                    main: true,
                    productId: 21,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '22p-miradas.jpeg',
                    main: true,
                    productId: 22,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '23d-control.jpeg',
                    main: true,
                    productId: 23,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '24p-womenAnimals.jpeg',
                    main: true,
                    productId: 24,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '25i-soledad.jpeg',
                    main: true,
                    productId: 25,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '26i-octava.jpeg',
                    main: true,
                    productId: 26,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '27i-butterfly.jpeg',
                    main: true,
                    productId: 27,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '28f-desolation.jpeg',
                    main: true,
                    productId: 28,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '29i-danza.jpeg',
                    main: true,
                    productId: 29,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
                {
                    file: '30i-lobo.jpeg',
                    main: true,
                    productId: 30,
                    createdAt: new Date(),
                    updatedAt: new Date(),
                },
            ],
            {}
        );
    },

    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Images', null, {});
    },
};
